services:
  webapi:
    image: myapp-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASS};Encrypt=false
    depends_on:
      - db

  db:
    image: custom-mssql-server
    build:
      context: .
      dockerfile: Dockerfile.sqlserver
    environment:
      SA_PASSWORD: ${DB_PASS}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  frontend:
    build:
      context: ./../Front/LivrariaVirtual/
      dockerfile: Dockerfile
    ports: 
    - "4200:4200"
    depends_on:
    - webapi